### ISSUE TITLE
Method $invoice->create() exits app and dosent return string

### ISSUE THREAD

**Issue by AliAmjid** [WebChemistry/invoice#11]
In WebChemistry\Invoice\Renderers\PDFRenderer on line 97 
`return $this->pdf->Output();`
This Echos the file and exits the app

There should Be 
`return $this->pdf->Output("S");`
This just returns string

**Comment by MartkCz** [comment]
I see `return $this->pdf->Output('S')` in dev-master https://github.com/contributte/invoice/blob/master/src/Renderers/PDFRenderer.php#L113

PS: you must run `composer require contributte/invoice:dev-master` and remove `webchemistry/invoice`

**Comment by AliAmjid** [comment]
Yep, my bad.  i had older version.
