### ISSUE TITLE
Uncaught Error: Class 'Contributte\Invoice\Data\Company' not found

### ISSUE THREAD

**Issue by igianni84** [WebChemistry/invoice#19]
Hi, as you can see, I receive the error

` Fatal error: Uncaught Error: Class 'Contributte\Invoice\Data\Company' not found in /Applications/MAMP/htdocs/Varie/ddt.php:3 Stack trace: #0 {main} thrown in /Applications/MAMP/htdocs/Varie/ddt.php on line 3`

My file php is:

```
<?php

$company = new Contributte\Invoice\Data\Company('John Doe', 'Los Angeles', 'Cavetown', '720 55', 'USA', '0123456789', 'CZ0123456789');
```

<img width="1380" alt="Schermata 2020-06-15 alle 16 37 35" src="https://user-images.githubusercontent.com/8584811/84670658-afb95c00-af26-11ea-84e5-82849b239771.png">

**Comment by MartkCz** [comment]
You must include composer's autoloader

```php
require __DIR__ . '/vendor/autoload.php';

$company = new Contributte\Invoice\Data\Company('John Doe', 'Los Angeles', 'Cavetown', '720 55', 'USA', '0123456789', 'CZ0123456789');
```

**Comment by igianni84** [comment]
Yes, I have do that, but the problem is the same
<img width="1034" alt="Schermata 2020-06-15 alle 16 44 35" src="https://user-images.githubusercontent.com/8584811/84671317-84833c80-af27-11ea-9b43-7b869e038d3e.png">

**Comment by MartkCz** [comment]
Please use dev-master version, v3 does not contain Contributte namespace

**Comment by igianni84** [comment]
Sorry... I have do that... but I have the same problem :(

**Comment by MartkCz** [comment]
It's weird, did you try to update autoloader? (`composer dumpautoload`)

**Comment by igianni84** [comment]
Yes, but nada...

**Comment by MartkCz** [comment]
What is the output of `composer info contributte/invoice`, please?

**Comment by igianni84** [comment]
<img width="787" alt="Schermata 2020-06-15 alle 18 44 18" src="https://user-images.githubusercontent.com/8584811/84683955-3e82a480-af38-11ea-955c-529b900a36a8.png">

Please see the screenshot

**Comment by MartkCz** [comment]
You haven't dev-master, 2 solutions:

First: install dev-master `composer require contributte/invoice:dev-master`

Second: use WebChemistry instead of Contributte e.g. Contributte\Invoice\Data\Company -> WebChemistry\Invoice\Data\Company

**Comment by igianni84** [comment]
Thanks, I receive this error

<img width="787" alt="Schermata 2020-06-15 alle 19 28 09" src="https://user-images.githubusercontent.com/8584811/84687665-6117bc00-af3e-11ea-941e-7d219991414f.png">

**Comment by MartkCz** [comment]
`composer require nette/utils:^3.0 contributte/invoice:dev-master`

**Comment by igianni84** [comment]
Perfect! Very thanks :)
