### ISSUE TITLE
missed dependency

### ISSUE THREAD

**Issue by Cuchulain** [WebChemistry/invoice#2]
Hello,
can You add dependency for **nette/utils**?

**Comment by MartkCz** [comment]
Hi, it doesn't need package nette/utils or am I wrong? Where is the problem?

Thanks

**Comment by Cuchulain** [comment]
Hello,
I try it as clean application (from scratch) and without nette/utils I get Fatal error.
The Invoice class use Nette\Utils\Strings.

btw: nice work, I like this library :)

**Comment by MartkCz** [comment]
You've right! Thanks.
