### ISSUE TITLE
v1.1.x - Nette extension broken in composer

### ISSUE THREAD

**Issue by marekrost** [WebChemistry/invoice#3]
Versions 1.1.1 and 1.1.2 in composer change a translation prefix in InvoiceExtension.php from `$builder->addDefinition($this->prefix('translator'))` to `$builder->addDefinition($this->prefix('translation'))`.

This seems to break Nette with the following exception:

> Service 'invoice.invoice': Reference to missing service 'invoice.translator'. in /srv/www/test/vendor/nette/di/src/DI/ContainerBuilder.php:582 caused by Nette\DI\ServiceCreationException: Reference to missing service 'invoice.translator'. in /srv/www/test/vendor/nette/di/src/DI/ContainerBuilder.php:874.

It can be fixed either by changing the prefix name back or changing the other uses from
`$this->prefix('@translator')` to `$this->prefix('@translation')`.

**Comment by MartkCz** [comment]
Thanks, can you try v1.1.3? I forgot release new version.

**Comment by marekrost** [comment]
1.1.3 works OK - no complaints from nette. Thank you :+1:
