### ISSUE TITLE
Version 4 or 5?

### ISSUE THREAD

**Issue by MartkCz** [WebChemistry/invoice#31]
- Create invoice pdf from svg (new repository for svg to pdf)
- Greyscale 
- Remove calculators and formatters (fixed string values)
- Simplify data classes
- PHP 8.0
- Replace template

@f3l1x release 3.1.0 or 4.0.0 for current version

**Comment by f3l1x** [comment]
I would release v3.1.0. Will do. :-)

**Comment by f3l1x** [comment]
Resolved
