### ISSUE TITLE
Contributte style

### ISSUE THREAD

**Issue by f3l1x** [WebChemistry/invoice#9]
- [x] readme
- [x] codestyle
- [x] tests 
- [x] phpstan

**Comment by MartkCz** [comment]
@f3l1x packagist

**Comment by f3l1x** [comment]
Done: https://packagist.org/packages/contributte/invoice

**Comment by f3l1x** [comment]
Please, take a look at contributte's bare repo and apply it for this package. :-)

https://github.com/contributte/contributte/tree/master/bare

**Comment by f3l1x** [comment]
ping @MartkCz

**Comment by adaamz** [comment]
phpstan here https://github.com/contributte/invoice/pull/12

**Comment by f3l1x** [comment]
Codestyle: https://github.com/contributte/invoice/commit/030c9ef8f0824ea2f8a33d3839ef9ebe30e44fa4
